gamenight/events/urls.py
from django.conf.urls import url

from . import views

app_name = 'events'
urlpatterns = [
    #handles requests for index
    url(r'^$', views.index, name='index'),
    #handles requests for specific event according to event_id
    url(r'^(?P<event_id>[0-9]+)/$', views.detail, name='detail'),
    #adding an attendee
    url(r'^(?P<event_id>[0-9]+)/add-attendee/$', views.add_attendee, name='add_attendee'),
    #removing an attendee
    url(r'^(?P<event_id>[0-9]+)/(?P<username_to_remove>[\w-]+)/remove-attendee/$', views.remove_attendee, name='remove_attendee'),
	#event creation
	url(r'^create/$', views.create_event, name='create',),
    #question creation
	url(r'^createquestion/(?P<event_id>[0-9]+)/$', views.create_question, name='createquestion',),
    #choice creation
	url(r'^createchoice/(?P<question_id>[0-9]+)/$', views.create_choice, name='createchoice',),
	#message creation
	url(r'^createmessage/(?P<event_id>[0-9]+)/$', views.create_message, name='createmessage',),
    #edits event
	url(r'^editevent/(?P<event_id>\d+)/edit/$', views.edit_event, name='editevent',),
    #edit question
    url(r'^editq/(?P<question_id>\d+)/$', views.edit_question, name='editquestion',),
    #edit message
    url(r'^editm/(?P<message_id>\d+)/$', views.edit_message, name='editmessage',),
    #delete question
    url(r'^deleteq/(?P<question_id>\d+)/$', views.delete_question, name='deletequestion',),
    #edit choice
    url(r'^editc/(?P<choice_id>\d+)/$', views.edit_choice, name='editchoice',),
    #delete choice
    url(r'^deletec/(?P<choice_id>\d+)/$', views.delete_choice, name='deletechoice',),
	#delete message
    url(r'^deletem/(?P<message_id>\d+)/$', views.delete_message, name='deletemessage',),
	#delete event
    url(r'^deleteevent/(?P<event_id>\d+)/$', views.delete_event, name='delete_event',),
	#vote
    url(r'^(?P<choice_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^public-events/$', views.public_events, name='public_events',),
	
	url(r'^searchevent/$', views.search_event, name='search_event')

    #creates choice
    #url(r'^addq/(?P<pk>\d+)/$', views.CreateChoiceView.as_view(), name='addchoice',),
    #VOID creates question
    #url(r'^addq/(?P<pk>\d+)/$', views.CreateQuestionView.as_view(), name='addquestion',),
    ]

gamenight/events/templates/events/attendee_manager.html
<div class='attending-users col-xs-16 col-md-16'>
	<div class="public_events_body panel panel-default panel-body col-md-14">
{% if is_organizer == True %}
<!--   <div class="add-attendee-form col-md-2 col-md-offset-4"> -->
    {% if add_form %}
      <form class="add-attendee" action="{% url 'events:add_attendee' event.id %}" method="POST" name="form" id="add-attendee">      
        {{add_form}}<button class="add-attendee-button btn btn-primary btn-md">Add</button>
        {% csrf_token %}
      </form>
      <br>
    {% endif %}
<!--   </div> -->
<!--   <div class="attendees col-md-3"> -->
  <h3>Attending Users</h3>
  {% for attendee in attendees %}
      {% if attendee.user != request.user %}
        <form class="remove-attendee" action="{% url 'events:remove_attendee' event.id attendee.user.username%}" method="POST" id="remove-attendee">
          <label>{{attendee.user.username}}</label>
          <button class="btn btn-primary btn-xs" >Remove</button>
          {% csrf_token %}
        </form>
      {% else %}
        <label>{{attendee.user.username}}</label>
      {% endif %}
  {% endfor %}
<!--   </div> -->
{% else %}
  <h3>Attending Users</h3>
  {% for attendee in attendees %}
    <li>{{attendee.user.username}}</li>
  {% endfor %}
{% endif %}
</div>
</div>

gamenight/events/templates/events/confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

gamenight/events/templates/events/create_choice.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "events/head.html" %}

  </head>
  <body>
    {% include "boardgames/navbar.html" %}
      <!--col-sm-3 col-md-2 col-md-offset-1 sidebar -->
      {% include "home/sidebar.html" %}
 <div class="public_events col-xs-12 col-md-5">
		<div class="panel panel-primary">
			<div class="public_events_heading panel-heading col-md-12">
				<h2>Create Choice</h2>

			</div>
			<div class="public_events_body panel panel-default panel-body col-md-12">
			  <form method="POST">
				  {% csrf_token %}
				  {{ form.as_p }}
				  <button type="submit">Submit</button>
				</form>				    
			</div>
		</div>
	</div>
    {% include "events/footer.html" %}
  </body>
</html>

gamenight/events/templates/events/create_event.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "events/head.html" %}

  </head>
  <body>
    {% include "boardgames/navbar.html" %}
      <!--col-sm-3 col-md-2 col-md-offset-1 sidebar -->
      {% include "home/sidebar.html" %}
<div class="public_events col-xs-12 col-md-5">
		<div class="panel panel-primary">
			<div class="public_events_heading panel-heading col-md-12">
				<h2>Create Event</h2>

			</div>
			<div class="public_events_body panel panel-default panel-body col-md-12">
			  <form method="POST">
				  {% csrf_token %}
				  {{ form.as_p }}
				  <button type="submit">Submit</button>
				</form>				    
			</div>
		</div>
	</div>

    {% include "events/footer.html" %}
  </body>
</html>

gamenight/events/templates/events/create_question.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "events/head.html" %}

  </head>
  <body>
    {% include "boardgames/navbar.html" %}

      <!--col-sm-3 col-md-2 col-md-offset-1 sidebar -->
      {% include "home/sidebar.html" %}
<div class="public_events col-xs-12 col-md-5">
		<div class="panel panel-primary">
			<div class="public_events_heading panel-heading col-md-12">
				<h2>Create Question</h2>

			</div>
			<div class="public_events_body panel panel-default panel-body col-md-12">
			  <form method="POST">
				  {% csrf_token %}
				  {{ form.as_p }}
				  <button type="submit">Submit</button>
				</form>				    
			</div>
		</div>
	</div>

    {% include "events/footer.html" %}
  </body>
</html>

gamenight/events/templates/events/edit_choice.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "events/head.html" %}

  </head>
  <body>
    {% include "boardgames/navbar.html" %}
    <div class="container">
      <!--col-sm-3 col-md-2 col-md-offset-1 sidebar -->
      {% include "home/sidebar.html" %}
   <div class="public_events col-xs-12 col-md-5">
		<div class="panel panel-primary">
			<div class="public_events_heading panel-heading col-md-12">
				<h2>Edit Choice</h2>

			</div>
			<div class="public_events_body panel panel-default panel-body col-md-12">
			  <form method="POST">
				  {% csrf_token %}
				  {{ form.as_p }}
				  <button type="submit">Submit</button>
				</form>				    
			</div>
		</div>
	</div>
    {% include "events/footer.html" %}
  </body>
</html>

gamenight/events/templates/events/edit_event.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "events/head.html" %}

  </head>
  <body>
    {% include "boardgames/navbar.html" %}

      <!--col-sm-3 col-md-2 col-md-offset-1 sidebar -->
      {% include "home/sidebar.html" %}
	<div class="public_events col-xs-12 col-md-5">
		<div class="panel panel-primary">
			<div class="public_events_heading panel-heading col-md-12">
				<h2>Edit Event</h2>

			</div>
			<div class="public_events_body panel panel-default panel-body col-md-12">
			  <form method="POST">
				  {% csrf_token %}
				  {{ form.as_p }}
				  <button type="submit">Submit</button>
				</form>				    
			</div>
		</div>
	</div>

	{% include "events/footer.html" %}
</body>
</html>

gamenight/events/templates/events/edit_message.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "events/head.html" %}

  </head>
  <body>
    {% include "boardgames/navbar.html" %}
    <div class="container">
      <!--col-sm-3 col-md-2 col-md-offset-1 sidebar -->
      {% include "home/sidebar.html" %}
 <div class="public_events col-xs-12 col-md-5">
		<div class="panel panel-primary">
			<div class="public_events_heading panel-heading col-md-12">
				<h2>Edit Message</h2>

			</div>
			<div class="public_events_body panel panel-default panel-body col-md-12">
			  <form method="POST">
				  {% csrf_token %}
				  {{ form.as_p }}
				  <button type="submit">Submit</button>
				</form>				    
			</div>
		</div>
	</div>
    {% include "events/footer.html" %}
  </body>
</html>

gamenight/events/templates/events/edit_question.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "events/head.html" %}

  </head>
  <body>
    {% include "boardgames/navbar.html" %}
      <!--col-sm-3 col-md-2 col-md-offset-1 sidebar -->
      {% include "home/sidebar.html" %}
  <div class="public_events col-xs-12 col-md-5">
		<div class="panel panel-primary">
			<div class="public_events_heading panel-heading col-md-12">
				<h2>Edit Question</h2>

			</div>
			<div class="public_events_body panel panel-default panel-body col-md-12">
			  <form method="POST">
				  {% csrf_token %}
				  {{ form.as_p }}
				  <button type="submit">Submit</button>
				</form>				    
			</div>
		</div>
	</div>
    {% include "events/footer.html" %}
  </body>
</html>

gamenight/events/templates/events/footer.html
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

gamenight/events/templates/events/head.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="This is where a description would go... IF I HAD ONE">
<meta name="author" content="This is where the author would go... IF I HAD ONE">

<title>{{ title|default:"GameNight" }}</title>

<!-- Bootstrap core CSS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'events/css/template.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'home/css/template.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'boardgames/css/template.css' %}" />
<script type="text/javascript" src="{% static 'events/javascript/events.js' %}"></script>




<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

gamenight/events/templates/events/index2.html
<span id="links">
<div class="datasection">
    <ul>
    {% for e in events %}
        <li class="listitem"><a href="{% url 'events:detail' e.id %}">{{ e }}</a></li>
    {% endfor %}
    </ul>
</div>

{% include "events/footer.html" %}
</span>

gamenight/events/templates/events/private_event.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'events/style.css' %}" />
{% block content %}
<h1 class="mainheading">This event is private.</h1>
<a href="{% url 'home:index' %}">Click here to return to home</a>
{% endblock %}

gamenight/events/templates/events/public_events.html
  <!-- <h1> Gamenight </h1> --><!-- 
  <a href="{% url 'authentication:signup' %}">Sign up</a>
  <a href="{% url 'authentication:login' %}">Log In</a>
  <p>
  <a href="{% url 'boardgames:index' %}">Board Games</a>
</p>
<p>
  <a href="{% url 'events:index' %}">Event Index</a>
</p> -->
	<div class="public_events col-sm-10 col-md-5">
		<div class="panel panel-primary">
			<div class="public_events_heading panel-heading col-md-12">
				<h2>Public Events</h2>
				<form class="event_search" role="search" method="get" action="{% url 'events:search_event' %}">
        <div class="input-group">
          {{ search_p.qq }}
            <button type="submit" class="search_button_public btn btn-primary">Submit</button>
        </div>
      </form>
			</div>
			<div class="public_events_body panel panel-default panel-body col-md-12">
				{% for event in events %}
					{% if forloop.counter|divisibleby:2 %}
						<div class="public_events_even">
						<a class="public_events_a" href="{% url 'events:detail' event.id %}">
							<b>{{event.title}}</b>
							<br>
							{{event.event_date}},
							{{event.location}}
							<br>
							<br>
							</a>
						</div>
					{% else %}
						<div class="public_events_odd">
						<a class="public_events_a" href="{% url 'events:detail' event.id %}">
							<b>{{event.title}}</b>
							<br>
							{{event.event_date}},
							{{event.location}}
							<br>
							<br>
						</div>
					{% endif %}
				{% endfor %}
				<div class="col-xs-12 col-md-offset-1">
			        {% if events.has_previous %}
			            <a href="?page={{ events.previous_page_number }}" class="boardgames_prev_page btn btn-primary col-md-2">previous</a>
			        {% else %}
			        	<span class="col-md-2"></span>
			        {% endif %}
			        <span class="current btn btn-primary col-md-3">
			            Page {{ events.number }} of {{ events.paginator.num_pages }}.
			        </span>
			        {% if events.has_next %}
			            <a href="?page={{ events.next_page_number }}" class="boardgames_next_page btn btn-primary col-md-2">next</a>
			        {% endif %}
				</div>
			</div>
		</div>
	</div>