gamenight/boardgames/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'boardgames'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^[?]pages=([0-9]+)/([?]results=([0-9]+))?/$', views.index, name='index'),
    # ex: /boardgames/100/101/ was to be sent to a view for url processing and redirecting 
    # url(r'^(?P<currBoardgameId>[0-9]+)(?:/([\w-]+))?/(?P<nextBoardgameId>[0-9]+)/$', views.next_detail, name='next_detail'),
    # ex: /boardgames/5/
    # url(r'^(?P<boardgameId>[0-9]+)(?:/([\w-]+))?/$', views.detail, name='detail'),
    # url(r'^(?P<boardgameId>[0-9]+)?/', include([
    #     url(r'^add_favourite/$', views.add_favourite, name='add_favourite'),
    #     url(r'^remove_favourite/$', views.remove_favourite, name='remove_favourite'),
    # ])),
    # The next two urls are in case multiple urls to the same destination is better than an optional path
    url(r'^(?P<boardgameId>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<boardgameId>[0-9]+)/add_favourite/$', views.add_favourite, name='add_favourite'),
    url(r'^(?P<boardgameId>[0-9]+)/remove_favourite/$', views.remove_favourite, name='remove_favourite'),
    url(r'^(?P<boardgameId>[0-9]+)?/([\w-]+)/$', views.detail, name='detail'),

    url(r'^search/$', views.search, name='search'),
]

gamenight/boardgames/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify

class BoardGame(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=20000)
    #pub_date is when the game was originally published, not when added to our db
    pub_date = models.DateField('date published', null=True)
    #rating on bgg as of being pulled from bgg
    bgg_rating = models.FloatField(default=0.0)
    bgg_bayesrating = models.FloatField(default=0.0)
    bgg_weight = models.FloatField(default=0.0)
    min_players = models.IntegerField(default=1)
    max_players = models.IntegerField(default=2)
    best_player_count = models.IntegerField(null=True)
    min_playtime = models.IntegerField(default=2)
    max_playtime = models.IntegerField(default=5)
    designed_by = models.ManyToManyField('Designer')
    img_link = models.URLField()
    tags = models.ManyToManyField('Tag')
    slug = models.SlugField(max_length=200, allow_unicode=True, null=True)

    def save(self, *args, **kwargs):
        # Newly created object, so set slug
        self.slug = slugify(self.name)
        super(BoardGame, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Designer(models.Model):
    name = models.CharField(max_length=1000)
    game = models.ManyToManyField(BoardGame)
    def __str__(self):
        return self.name

class Tag(models.Model):
    tag_name = models.CharField(max_length=5000)
    description = models.CharField(max_length=10000)
    games = models.ManyToManyField(BoardGame)
    def __str__(self):
        return self.tag_name

gamenight/boardgames/templates/boardgames/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "boardgames/head.html" %}
  </head>
 <body>
 {% include "boardgames/navbar.html" %}

	<div class="boardgame_detail col-xs-12 col-md-8 col-md-offset-2">
		<div class="panel panel-primary">
			<div class="boardgame_detail_heading panel-heading col-md-12">
				<h2>{{boardgame.name}}</h2>
			</div>
	<div class="boardgame_detail_info panel panel-default panel-body col-md-12">
		<div class="boardgame_detail_info_image col-md-3">
		<!--Boardgame Image-->
			{% if boardgame.img_link %}
				<img src="{{boardgame.img_link}}" alt="{{boardgame.name}}" height="300" width="300">
			{% else %}
			{% load static %}
				<span><img src="{% static 'boardgames/images/placeholder.png' %}" alt="placeholder" height="300" width="300"></span>
			{% endif %}
		</div>
		<div class="boardgame_detail_info_misc col-md-6">
			<div class="boardgame_detail_info_misc_header">
					<div class="rating">
						<div id="octagon">
							<p id="bgg_bayesrating">{{boardgame.bgg_bayesrating|floatformat:2}}</p>
						</div>
					</div>
					<!--Other Things in Header Area Go Here!-->
			</div>
			<div class="boardgame_detail_info_misc_table col-md-8">
			<!--Table of Basic Data-->
				<table class="table table-striped">
					<tr>
						<td class="players">Players: </td>
						<td>Min: {{boardgame.min_players}}</td>
						<td>Max: {{boardgame.max_players}}</td>
					</tr>
					<tr>
						<td class="playtime">Playtime:</td>
						<td>Min: {{boardgame.min_playtime}} mins</td>
						<td>Max: {{boardgame.max_playtime}} mins</td>
					</tr>
					<tr></tr>
				</table>
			</div>
			<div class="boardgame_detail_info_misc_other col-md-8">
			<!--Other Data Such As Pub Data, Designer, etc.-->
			<p>Designer:
				{{designers|join:", "}}
				</p>
				<p>Weight: {{boardgame.bgg_weight|floatformat:2}}</p>
				<p>Published Date: {{boardgame.pub_date}}</p>
				<p>Best Player Count: {{boardgame.best_player_count}}</p>
			</div>
		</div>
		<div class="boardgame_detail_info_buttons col-md-12">
			{% if favourite %}
			<form class="favorited_button" action="{% url 'boardgames:remove_favourite' boardgame.id %}" method="POST" id="favorited_form">
				<!-- <input id="submit" type="button" value=" Favorite"></input> -->
				{% csrf_token %}
			</form>
			<button class="favorited_button btn btn-xs" type="submit" form="favorited_form" value="Submit"><span class="glyphicon glyphicon-heart"></span> Favourited</button>
			{% else %}
			<form class="favorite_button" action="{% url 'boardgames:add_favourite' boardgame.id %}" method="POST" id="favorite_form">
				<!-- <input id="submit" type="button" value=" Favorite"></input> -->
				{% csrf_token %}
			</form>
			<button class="favorite_button btn btn-xs" type="submit" form="favorite_form" value="Submit"><span class="glyphicon glyphicon-heart"></span> Favourite</button>
			{% endif %}
		</div>
	</div>
	<div class="boardgame_detail_description panel panel-default panel-body col-md-12">
	<h3>Description</h3>
	<div class="description">
		<p>{{boardgame.description}}</p>
	</div>
	</div>
	<div class="boardgame_detail_tags panel panel-default panel-body col-md-12">
		<div class="tags">
		<h4>Tags</h4>
		{% for tag in boardgame.tag_set.all %}
		    <span tabindex="0" class="tag_label_popover label label-primary" data-toggle="popover" data-trigger="focus" data-placement="top" data-content="{{ tag.description }}">{{ tag.tag_name }}</span>
		{% endfor %}
		</div>
	</div>
		<div class="reviews">
		</div>
	<div class="col-md-8 col-md-offset-4">
		{% if prev_id != None %}
			<a href="?next={{prev_id}}" class="boardgame_detail_next_page btn btn-primary col-md-2">prev</a>
		{% endif %}
		{% if next_id != None %}
			<a href="?next={{next_id}}" class="boardgame_detail_next_page btn btn-primary col-md-2">next</a>
		{% endif %}
	</div>
</div>
</div>
{% include "boardgames/footer.html" %}
</body>

gamenight/boardgames/templates/boardgames/footer.html
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    {% load static %}
    <script src="{% static 'boardgames/javascript/boardgame.js' %}"></script>

gamenight/boardgames/templates/boardgames/head.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="This is where a description would go... IF I HAD ONE">
<meta name="author" content="This is where the author would go... IF I HAD ONE">

<title>{{ title|default:"GameNight" }}</title>

<!-- Bootstrap core CSS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></script><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'boardgames/css/template.css' %}" />


<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

gamenight/boardgames/templates/boardgames/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "boardgames/head.html" %}
  </head>
<body>
	{% include "boardgames/navbar.html" %}
	
	<div class="col-xs-12 col-md-7 col-md-offset-2">
		<div class="boardgames panel panel-default panel-chart">
			<div class="boardgames_heading panel-heading col-md-12">
			<h4 class="col-md-5"> Board Game List</h4>
			<div class="boardgames_dropdown col-md-4 col-md-offset-3">
			<!-- if time permits replace with a href link "?results='value' instead of a form to keep
			 consistent results per page and url = '?page='num'?results='value'" like page probably as a dropdown-->
			<form action="" method="get">
				<select name="results" class="btn btn-primary dropdown boardgames_select">
					<option value="10 {{boardgames.number}}">10 per page</option>
					<option value="20 {{boardgames.number}}">20 per page</option>
					<option value="50 {{boardgames.number}}">50 per page</option>
					<option value="-1 {{boardgames.number}}">All</option>
				</select>
				<input type="submit" Value="Go" class="boardgames_select_submit">
			</form>
			</div>
			</div>
			<div class="boardgames_body panel panel-body col-md-12">
				{% for boardgame in boardgames %}
				<!-- <div class="col-xs-12 col-md-7 col-md-offset-2"> -->
					<div class="boardgame panel panel-primary">
						<div class="boardgame_heading panel-heading col-md-12">
							<h3 style="color:white" class="boardgame_title panel-title"> <span class="boardgame_title_name col-md-10">{{boardgame.name}}</span><span class="boardgame_title_star glyphicon glyphicon-star col-md-1"></span><span class="boardgame_title_bayes col-md-1">{{boardgame.bgg_bayesrating|floatformat:2}}</span></h3>
						</div>
						<div class="boardgame_body panel-body" data-counter="{{ forloop.counter}}">
						<table>
							<tr>
								{% if boardgame.img_link %}
									<td><span class="col-md-3"><a href="{% url 'boardgames:detail' boardgame.id boardgame.name|slugify %}" class="boardgame_detail_link"><img src="{{boardgame.img_link}}" alt="{{boardgame.name}}" height="100" width="100"></a></span></td>
								{% else %}
									{% load static %}
									<td><span class="col-md-9"><a href="{% url 'boardgames:detail' boardgame.id boardgame.name|slugify %}" class="boardgame_detail_link"><img src="{% static 'boardgames/images/placeholder.png' %}" alt="placeholder" height="100" width="100"></a></span></td>
								{% endif %}
					    		<td><span class="boardgame_description">{{boardgame.description}}</span></td>
				    		</tr>
			    		</table>
			    		</div>
					</div>
				<!-- </div> -->
				{% endfor %}
				<!-- TODO: Add infinite scroll -->
				<div class="col-xs-12 col-md-offset-1">
					        {% if boardgames.has_previous %}
					            <a href="?page={{ boardgames.previous_page_number }}" class="boardgames_prev_page btn btn-primary col-md-2">previous</a>
					        {% else %}
					        	<span class="col-md-2"></span>
					        {% endif %}
					        <span class="current btn btn-primary col-md-2">
					            Page {{ boardgames.number }} of {{ boardgames.paginator.num_pages }}.
					        </span>
					        <form action="" method="get">
					        	<!-- {% csrf_token %} -->
    							<input id="want_page" type="text" name="page" value="1" class="input-sm col-md-3">
    							<input type="submit" value="OK" class="boardgames_page_submit col-md-1">
							</form>
					        {% if boardgames.has_next %}
					            <a href="?page={{ boardgames.next_page_number }}" class="boardgames_next_page btn btn-primary col-md-2">next</a>
					        {% endif %}
				</div>
			</div>
		</div>
	</div>
<!-- Shows individual pages. Needs a paginator library to limit amount of pages	 
	<ul class="pagination nav navbar-nav">
    	{% if boardgames.has_previous %}
            <li><a href="?page={{ boardgames.previous_page_number }}">Prev</a></li>
    	{% endif %}
    	{% for page in boardgames.paginator.page_range %}
    		{% if boardgames.paginator.num_pages > 1 %}
    			<li class="{% if boardgames.number == page  %}active{% endif %}"><a href="?page={{page }}">{{ page }}</a></li>
    		{% endif %}
    	{% endfor %}

    {% if boardgames.has_next %}
        <li> <a href="?page={{ boardgames.next_page_number }}">Next</a></li>
    {% endif %}
 </ul> -->
{% include "boardgames/footer.html" %}
</body>

gamenight/boardgames/templates/boardgames/navbar.html
<nav class="main_navbar navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {% load static %}
      <a class="navbar-brand" href="{% url 'home:index' %}"><img src="{% static 'boardgames/images/logo.png' %}"></a>
      </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'home:index' %}">Home<span class="sr-only">(current)</span></a></li>
        <!--Add when user is available-->
        {% if user.is_authenticated %}
        <li><a href="{% url 'authentication:profile' %}">Profile</a></li>
        <li><a href="{% url 'boardgames:index' %}">Boardgames</a></li>
        <li><a href="{% url 'events:index' %}">Events</a></li>
        <li><a href="{% url 'authentication:logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'boardgames:index' %}">Boardgames</a></li>
        <li><a href="{% url 'authentication:signup' %}">Create Account</a></li>
        <li><a href="{% url 'authentication:login' %}">Login</a></li>
        {% endif %}

<!--    Dropdown If Needed     
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
        
      </ul>
      <form class="navbar-form navbar-right" role="search" method="get" action="{% url 'boardgames:search' %}">
        <div class="input-group" width="100">
          {{ search.q }}
          <span class="input-group-btn">
            <button type="submit" class="search_button btn btn-default">Submit</button>
          </span>
        </div>
      </form>
    </div>
  </div>
</nav>

gamenight/boardgames/templates/boardgames/search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "boardgames/head.html" %}
  </head>
<body>
	{% include "boardgames/navbar.html" %}
	<div class="col-xs-12 col-md-7 col-md-offset-2">
		<div class="boardgames panel panel-default panel-chart">
			<div class="boardgames_heading panel-heading col-md-12">
			<h4 class="col-md-5"> Search Results</h4>
			</div>
			{% if boardgames %}
			<div class="boardgames_body panel panel-body col-md-12">
				{% for boardgame in boardgames %}
				<!-- <div class="col-xs-12 col-md-7 col-md-offset-2"> -->
					<div class="boardgame panel panel-primary">
						<div class="boardgame_heading panel-heading col-md-12">
							<h3 style="color:white" class="boardgame_title panel-title"> <span class="boardgame_title_name col-md-10">{{boardgame.name}}</span><span class="boardgame_title_star glyphicon glyphicon-star col-md-1"></span><span class="boardgame_title_bayes col-md-1">{{boardgame.bgg_bayesrating|floatformat:2}}</span></h3>
						</div>
						<div class="boardgame_body panel-body" data-counter="{{ forloop.counter}}">
						<table>
							<tr>
								{% if boardgame.img_link %}
									<td><span class="col-md-3"><a href="{% url 'boardgames:detail' boardgame.id boardgame.name|slugify %}" class="boardgame_detail_link"><img src="{{boardgame.img_link}}" alt="{{boardgame.name}}" height="100" width="100"></a></span></td>
								{% else %}
									{% load static %}
									<td><span class="col-md-9"><a href="{% url 'boardgames:detail' boardgame.id boardgame.name|slugify %}" class="boardgame_detail_link"><img src="{% static 'boardgames/images/placeholder.png' %}" alt="placeholder" height="100" width="100"></a></span></td>
								{% endif %}
					    		<td><span class="boardgame_description">{{boardgame.description}}</span></td>
				    		</tr>
			    		</table>
			    		</div>
					</div>
				<!-- </div> -->
				{% endfor %}
				<!--If Pages Start Working-->
			<div class="col-xs-12 col-md-offset-1">
					        {% if boardgames.has_previous %}
					            <a href="?page={{ boardgames.previous_page_number }}?q={{query}}" class="boardgames_prev_page btn btn-primary col-md-2">previous</a>
					        {% else %}
					        	<span class="col-md-2"></span>
					        {% endif %}
					        <span class="current btn btn-primary col-md-2">
					            Page {{ boardgames.number }} of {{ boardgames.paginator.num_pages }}.
					        </span>
					        {% if boardgames.has_next %}
					            <a href="?page={{ boardgames.next_page_number }}?q={{query}}" class="boardgames_next_page btn btn-primary col-md-2">next</a>
					        {% endif %}
				</div>
	        {% else %}
	        <div class="col-md-12 text-center">
	          <h1>Your search returned no results</h1>
	        </div>
	        {% endif %}
      		</div>
		</div>
	</div>
{% include "boardgames/footer.html" %}
</body>